--BD2 - 2o Bim - Atividade de SQL - Exercícios de DDL - Comentários em tabelas - Parte 5

COMMENT ON TABLE ITEM_PRODUTO IS 'TABELA QUE ARMAZENA UM ITEM DE UM PRODUTO';
COMMENT ON COLUMN ITEM_PRODUTO.CODIGO_PRO IS 'COLUNA QUE COMPÕE A CHAVE PRIMARIA DA TABELA E FOREIGN KEY QUE SE REFERE À COLUNA CODIGO DA TABELA PRODUTO';
COMMENT ON COLUMN ITEM_PRODUTO.NUMERO_PED IS 'COLUNA QUE COMPÕE A CHAVE PRIMARIA DA TABELA E FOREIGN KEY QUE SE REFERE A COLUNA NUMERO DA TABELA PEDIDO';
COMMENT ON COLUMN ITEM_PRODUTO.QUANTIDADE IS 'COLUNA QUE REPRESETA A QUANTIDADE DO PRODUTO REFERIDO';
COMMENT ON COLUMN ITEM_PRODUTO.PRECO_UNITARIO IS 'COLUNA QUE REPRESENTA O PRECO UNITARIO DO PRODUTO REFERIDO';
COMMENT ON COLUMN ITEM_PRODUTO.VALOR_ITEM IS 'VALOR O ITEM';