/* BD2 - 2o Bim -Atividade de SQL - Exercícios de DDL - Tabelas do Projeto Pedido - Parte 2
Queries implementadas na linguagem SQL aplicadas no SGBDR Oracle, apoiadas no
SqlDeveloper. Utilizar o MER Físico e BD Pedido disponibilizado para treinamento da disciplina
de Banco de Dados.
1) Criar as tabelas associativas: PEDIDO, ESTOQUE, CAPACIDADE_ESTOQUE e
ITEM_PRODUTO. Não incluir na criação destas tabelas as chaves primária (PK) e
chaves estrangeiras (FK). Substituir todos os tipos de dados INTEGER do modelo por
NUMBER.
2) Criar as constraints de chave primária (primary key) para as tabelas associativas.
3) Criar as constraints das chaves estrangeiras (foreing key) para as tabelas associativas.*/

DROP TABLE PEDIDO CASCADE CONSTRAINTS;
DROP TABLE ESTOQUE CASCADE CONSTRAINTS;


CREATE TABLE PEDIDO (
NUMERO          NUMBER(6),
DATA            DATE NOT NULL,
PRAZO_ENTREGA   DATE,
RUA             VARCHAR2(80),
NR              NUMBER(4),
BAIRRO          VARCHAR2(50),
COMPLEMENTO     VARCHAR2(100),
CIDADE          VARCHAR2(50),
UF              VARCHAR2(2),
CEP             VARCHAR2(10),
TOTAL_FATURA    NUMBER(8,2),
CODIGO_CLI      NUMBER NOT NULL,
MATRICULA_VEN   NUMBER NOT NULL
);

CREATE TABLE ESTOQUE (
DATA_ENTRADA        DATE,
CODIGO_PRO          NUMBER,
CODIGO_PRA          NUMBER(3),
QUANTIDADE          NUMBER(5) NOT NULL,
DATA_VALIDADE       DATE
);

CREATE TABLE CAPACIDADE_ESTOQUE (
CODIGO_PRO NUMBER,
CODIGO_PRA NUMBER,
QUANTIDADE NUMBER(5) NOT NULL
);

CREATE TABLE ITEM_PRODUTO(
CODIGO_PRO          NUMBER,
NUMERO_PED          NUMBER(6),
QUANTIDADE          NUMBER(5) NOT NULL,
PRECO_UNITARIO      NUMBER(5,2) NOT NULL,
VALOR_ITEM          NUMBER(7,2)
);

ALTER TABLE PEDIDO
ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NUMERO)
ADD CONSTRAINT FK_PED_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE (CODIGO)
ADD CONSTRAINT FK_PED_VENDEDOR FOREIGN KEY (MATRICULA_VEN) REFERENCES VENDEDOR (MATRICULA)
;


ALTER TABLE ESTOQUE 
ADD CONSTRAINT PK_ESTOQUE PRIMARY KEY(DATA_ENTRADA, CODIGO_PRO, CODIGO_PRA)
ADD CONSTRAINT  FK_EST_PRODUTO FOREIGN KEY (CODIGO_PRO) REFERENCES PRODUTO (CODIGO)
ADD CONSTRAINT FK_EST_PRATELEIRA FOREIGN KEY (CODIGO_PRA) REFERENCES PRATELEIRA (CODIGO)
;

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT PK_CAPACIDADE_ESTOQUE PRIMARY KEY (CODIGO_PRO, CODIGO_PRA)
ADD CONSTRAINT  FK_CAP_EST_PRODUTO FOREIGN KEY (CODIGO_PRO) REFERENCES PRODUTO (CODIGO)
ADD CONSTRAINT FK_CAP_EST_PRATELEIRA FOREIGN KEY (CODIGO_PRA) REFERENCES PRATELEIRA (CODIGO)
;

ALTER TABLE ITEM_PRODUTO 
ADD CONSTRAINT PK_ITEM_PRODUTO PRIMARY KEY (CODIGO_PRO, NUMERO_PED)
ADD CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (CODIGO_PRO) REFERENCES PRODUTO (CODIGO)
ADD CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (NUMERO_PED) REFERENCES PEDIDO (NUMERO)
;

