-- BD2 - 2o Bim -Atividade de SQL - Exercícios de DDL - Tabelas do Projeto Pedido - Parte 
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE FONE_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE PF CASCADE CONSTRAINTS;
DROP TABLE PJ CASCADE CONSTRAINTS;
DROP TABLE VENDEDOR CONSTRAINTS;
DROP TABLE FONE_VENDEDOR CASCADE CONSTRAINTS;
DROP TABLE PRODUTO CASCADE CONSTRAINTS;
DROP TABLE PRATELEIRA CASCADE CONSTRAINTS;

CREATE TABLE CLIENTE (
CODIGO          NUMBER,
NOME            VARCHAR2(60) NOT NULL,
RUA             VARCHAR2(80) NOT NULL,
NR              NUMBER(4)       NOT NULL,          
BAIRRO          VARCHAR2(50) NOT NULL,
COMPLEMENTO     VARCHAR2(100) NULL,
CIDADE          VARCHAR2(50) NOT NULL,
UF              VARCHAR2(2) NOT NULL,
CEP             VARCHAR2(10) NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY  (CODIGO) 
);

SELECT * FROM USER_TABLES WHERE TABLE_NAME IN ('CLIENTE');

CREATE TABLE FONE_CLIENTE (
NUMERO          VARCHAR2(14),
CODIGO_CLI      NUMBER,
CONSTRAINT PK_FONE_CLIENTE PRIMARY KEY (NUMERO,CODIGO_CLI),
CONSTRAINT FK_FONE_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE (CODIGO)
);

SELECT * FROM USER_TABLES WHERE TABLE_NAME IN ('FONE_CLIENTE');

CREATE TABLE PF(
CODIGO_CLI          NUMBER,
CNPF                VARCHAR2(14) NOT NULL,
RG                  VARCHAR2(10) NOT NULL,
DATA_NASCIMENTO     DATE        NOT NULL,
CONSTRAINT PK_CLIENTE_PF PRIMARY KEY (CODIGO_CLI),
CONSTRAINT FK_PF_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE (CODIGO)
);

SELECT * FROM USER_TABLES WHERE TABLE_NAME IN ('PF');


CREATE TABLE PJ(
CODIGO_CLI          NUMBER,
CNPJ                VARCHAR2(19) NOT NULL,
IJ                  VARCHAR2(10) NOT NULL,
DATA_FANTASIA       VARCHAR2(60) NOT NULL,
CONSTRAINT PK_CLIENTE_PJ PRIMARY KEY (CODIGO_CLI),
CONSTRAINT FK_PJ_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE (CODIGO)
);

SELECT * FROM USER_TABLES WHERE TABLE_NAME IN ('PJ');

CREATE TABLE VENDEDOR(
MATRICULA           NUMBER,
NOME                VARCHAR2(60) NOT NULL,
CNPF                VARCHAR2(14) NOT NULL,
CONSTRAINT PK_VENDEDOR PRIMARY KEY (MATRICULA)
);

SELECT * FROM USER_TABLES WHERE TABLE_NAME IN ('VENDEDOR');

CREATE TABLE FONE_VENDEDOR(
NUMERO              VARCHAR2(14),
MATRICULA_VEN       NUMBER,
CONSTRAINT PK_FONE_VENDEDOR PRIMARY KEY (NUMERO, MATRICULA_VEN),
CONSTRAINT FK_FONE_VENDEDOR FOREIGN KEY (MATRICULA_VEN) REFERENCES VENDEDOR (MATRICULA)
);

SELECT * FROM USER_TABLES WHERE TABLE_NAME IN ('FONE_VENDEDOR');

CREATE TABLE PRODUTO(
CODIGO          NUMBER,
DESCRICAO       VARCHAR2(80) NOT NULL,
UNID_MEDIDA     VARCHAR2(10) NOT NULL,
CONSTRAINT PK_PRODUTO PRIMARY KEY (CODIGO)
);

SELECT * FROM USER_TABLES WHERE TABLE_NAME IN ('PRODUTO');

CREATE TABLE PRATELEIRA(
CODIGO          NUMBER(3),
DESCRICAO       VARCHAR2(50) NOT NULL,
NUMERO_SECOES   NUMBER(2) NOT NULL,
CONSTRAINT PK_PRATELEIRA PRIMARY KEY (CODIGO)
);

SELECT * FROM USER_TABLES WHERE TABLE_NAME IN ('PRATELEIRA');